CICDV2

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -22,6 +22,35 @@ jobs:
       - name: Install dependencies
         run: yarn install
 
+      - name: Run storybook
+        run: yarn storybook
+
+      - name: Run tests with coverage
+        run: yarn test --coverage
+
+      # - name: Check coverage threshold
+      #   run: |
+      #     COVERAGE=$(grep -o '"statements": [0-9.]*' ./coverage/coverage-summary.json | awk '{print $2}')
+      #     if (( $(echo "$COVERAGE < 50.0" |bc -l) )); then
+      #       echo "Test coverage ($COVERAGE%) is below the required threshold of 50%."
+      #       exit 1
+      #     else
+      #       echo "Test coverage ($COVERAGE%) meets the required threshold."
+      #     fi
+
+      # - name: Upload coverage to Codecov
+      #   uses: codecov/codecov-action@v4
+      #   with:
+      #     token: ${{ secrets.CODECOV_TOKEN }}
+      #     files: ./coverage/lcov.info
+      #     flags: unittests
+      #     name: codecov-umbrella
+      #     fail_ci_if_error: true
+      #     verbose: true
+
+      # - name: Build Storybook
+      #   run: yarn storybook:build
+
   deploy:
     runs-on: ubuntu-latest
     needs: build
@@ -42,3 +71,10 @@ jobs:
 
       - name: Deploy to AWS with SST
         run: npx sst deploy --stage prod
+
+      - name: Deploy Storybook
+        uses: JamesIves/github-pages-deploy-action@v4
+        with:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BRANCH: gh-pages
+          FOLDER: storybook-static
